# exclude:
  # - vendor
# exclude:  
  # - Gemfile
  # - Gemfile.lock
  # - node_modules
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
  # - cache/  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag  
   
# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
# - {name: 'Interesting Facts',  url: 'facts'}
# - {name: 'Learning Resources', url: 'resources'}
# - {name: 'Sample Posts',       url: 'sample-posts'}
# - {name: 'Documentation',      url: 'documentation'}
# - {name: 'About',              url: 'about'}
# - {name: 'Contact',            url: 'contact'}
- {name: 'About',                 url: 'about'}
- {name: 'Affiliates',            url: 'affiliates'}
- {name: 'Events',                url: 'events'}
# - {name: 'SurfGod HtB for iOS',   url: 'surfgodhtb'}
- {name: 'Videos',                url: 'videos'}
- {name: 'VocalYoga',             url: 'vocalyoga'}
- {name: 'Abundance Course App',  url: 'abundancecourse'}
- {name: 'Contact',               url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link:  'https://instagram.com/clearfromwithin'}
- {icon: 'youtube', link:    'https://youtube.com/clearfromwithin'}
- {icon: 'facebook', link:   'https://www.facebook.com/clearfromwithin'}
- {icon: 'twitter', link:    'https://twitter.com/clearfromwithin'}
# - {icon: 'envelope', link:   'mailto:hello@paulle.ca'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text (commenting out next lines does not remove the new/old option)
pagination:  
next_page: 'Newer'
previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

# post_date_prefix: 'Written on'
